export const metadata = {
  title: 'Next.js Test',
  description: 'Generated by Next.js test',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <h1 style={{backgroundColor:'green'}}>HEADER</h1>
        {children}
        <h3 style={{backgroundColor:'yellow'}}>footer</h3>
      </body>
    </html>
  )
}
